---
title: "RF_practice"
author: "Yujui Chang"
date: "2021/9/24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## homeprice
```{r}
H = read.csv(url("http://fs2.american.edu/~baron/627/R/HOME_SALES.csv"))
H$ID <- NULL
H
```

```{r}
set.seed(1)
n = nrow(H)
z = sample(n, n*0.8) # 0.8 for train, 0.2 for test
```

# train RF model
```{r}
library(randomForest)
train_RF = randomForest(SALES_PRICE~., data= H[z,])
train_RF
```

# Why 3 ? Rule of thumb: usually m ~= root(p)
```{r}
p = ncol(H)-1 # deduct response
p
sqrt(p) # No. of variables tried at each split: 3
```

# test model
```{r}
yhat = predict(train_RF, newdata= H[-z,])

sqrt(mean((yhat - H[-z,]$SALES_PRICE)^2)) # RMSE
```

# tuning and test model again
```{r}
train_RF = randomForest(SALES_PRICE~., data= H[z,],  mtry= 11) # 3 -> 11 variables
train_RF

yhat = predict(train_RF, newdata= H[-z,])
sqrt(mean((yhat - H[-z,]$SALES_PRICE)^2)) # RMSE: 3 is better than 11
```

# try different trees 
```{r}
train_RF = randomForest(SALES_PRICE~. , data= H[z, ], mtry= 11, ntree= 100) # 3 -> 11 variables, 500 -> 100 trees
yhat = predict(train_RF, newdata= H[-z, ])
sqrt(mean((yhat - H[-z, ]$SALES_PRICE)^2)) # RMSE is going up
```

# find the best trees and variables
```{r}
set.seed(1)
n = nrow(H)
z = sample(n, n*0.8)

RMSEP = rep(0,p) # p = 11 predictors. try every predictors to find the best random forest
optimaltrees = rep(0,p)

for(k in 1:p){
  train_RF = randomForest(SALES_PRICE~., data= H[z,], mtry= k)
  optimaltrees[k] = which.min(train_RF$mse) # In each variables selection, number with lowest mse = optimal trees.
  
  train_RF = randomForest(SALES_PRICE~., data= H[z,], mtry= k, ntree= optimaltrees[k])
  yhat = predict(train_RF, newdata = H[-z,])
  RMSEP[k] = sqrt(mean((yhat- H$SALES_PRICE[-z])^2))
}

plot(train_RF$mse)
```

```{r}
which.min(RMSEP)
optimaltrees[4]

# optimize with lowest rmse. tuned random forest: m= 4 variables, n= 288 trees
```

```{r}
# fit best random forest trees
best_RF = randomForest(SALES_PRICE~., data= H[z, ], mtry= 4, ntree= 288) 
best_RF
```

```{r}
importance(best_RF) 
varImpPlot(best_RF)
```
